spring:
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: http://localhost:9080/auth/realms/jhipster
        registration:
          oidc:
            client-id: jhipster-control-center
            client-secret: jhipster-control-center
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/auth/realms/jhipster
  cloud:
    gateway:
      default-filters:
        - TokenRelay
